### PR TITLE
fix multiple files conversion

### PR DESCRIPTION
**Pull request by kifirkin**
fixes conversion of first read input file to multiple outputs
now it converts multiple inputs to exact multiple outputs

### CODE REVIEW

**Comment by patillacode** [comment]
Hi @kifirkin 

Thanks for your PR, I have taken a look and I tested without issues, although, before I merge your enhancements I would to understand what is the issue you are addressing.
Could you please let me know with a quick message?  Maybe an example?

Also, are there any changes needed either in the tests or in the README?

Thanks again.

**Comment by kifirkin** [comment]
Hi @patillacode ! Thanks for your reply!

Steps to reproduce my issue:

1. Go to folder where many video files with same extension (in my case there are many `avi` files that need to be converted. 
2. Then start converter like this: `converter-cli video --multiple --verbose`
3.  Select the following options: 
* Convert to: `1 - mp4`
* Source folder path: `./`
* Extension: `avi`
* Destination folder: `./`

What you've got then as we could see here https://github.com/patillacode/converter-cli/blob/master/convert/commands/base.py#L93 and here https://github.com/patillacode/converter-cli/blob/master/convert/commands/base.py#L93 is single input video to be converted for the multiple output paths.

To fix this issue we just need to aggregate two separate lists for inputs and outputs.

Also I think tests doesn't cover this situation at all. They passed before and after my commit without problems.

**Comment by patillacode** [comment]
Oh, wow, I see it now...

I just ran it again and indeed this issue is there both for audio and video conversions (makes sense since both use the same flow)
I ran your fix and it is working, merging it!

Thanks a lot @kifirkin

**Comment by kifirkin** [comment]
@patillacode awesome!

By the way thank you for your work! This tool saved my day 😅

**Pull request merged**
